package com.geekarms.ws.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.12
 * 2017-02-08T17:05:03.968+08:00
 * Generated source version: 3.0.12
 * 
 */
@WebService(targetNamespace = "http://interfaces.ws.geekarms.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://interfaces.ws.geekarms.com/", className = "com.geekarms.ws.interfaces.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://interfaces.ws.geekarms.com/", className = "com.geekarms.ws.interfaces.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.geekarms.ws.interfaces.User> findAll();

    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://interfaces.ws.geekarms.com/", className = "com.geekarms.ws.interfaces.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://interfaces.ws.geekarms.com/", className = "com.geekarms.ws.interfaces.AddUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.geekarms.ws.interfaces.User addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findById", targetNamespace = "http://interfaces.ws.geekarms.com/", className = "com.geekarms.ws.interfaces.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://interfaces.ws.geekarms.com/", className = "com.geekarms.ws.interfaces.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.geekarms.ws.interfaces.User findById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findUserMap", targetNamespace = "http://interfaces.ws.geekarms.com/", className = "com.geekarms.ws.interfaces.FindUserMap")
    @ResponseWrapper(localName = "findUserMapResponse", targetNamespace = "http://interfaces.ws.geekarms.com/", className = "com.geekarms.ws.interfaces.FindUserMapResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.geekarms.ws.interfaces.MapUserType findUserMap();
}
